"""
SadTalker engine — audio-driven portrait animation.

Takes audio + portrait, produces a talking-head video with lip sync,
head motion, and facial expressions derived from the audio signal.

This is the default engine. Works end-to-end without any additional models.
"""

import os
import glob
import subprocess

from engines.base_engine import BaseEngine

WORK_DIR = "/app/SadTalker"


class SadTalkerEngine(BaseEngine):
    name = "sadtalker"

    def generate(self, audio_path, portrait_path, output_dir, quality="720p"):
        cmd = [
            "python", "inference.py",
            "--driven_audio", audio_path,
            "--source_image", portrait_path,
            "--result_dir", output_dir,
            "--enhancer", "gfpgan",
            "--expression_scale", "1.0",
            "--still",
            "--preprocess", "full",
        ]

        if quality == "720p":
            cmd.extend(["--size", "512"])
        elif quality == "1080p":
            cmd.extend(["--size", "768"])
        else:
            cmd.extend(["--size", "256"])

        print(f"[sadtalker] Running: {' '.join(cmd)}")

        result = subprocess.run(
            cmd,
            cwd=WORK_DIR,
            capture_output=True,
            text=True,
            timeout=180,
        )

        if result.returncode != 0:
            print(f"[sadtalker] stderr: {result.stderr}")
            raise RuntimeError(
                f"SadTalker inference failed: {result.stderr[-500:]}"
            )

        print(f"[sadtalker] stdout: {result.stdout[-500:]}")

        video_files = (
            glob.glob(os.path.join(output_dir, "*.mp4"))
            + glob.glob(os.path.join(output_dir, "*.webm"))
        )
        if not video_files:
            video_files = (
                glob.glob(os.path.join(output_dir, "**", "*.mp4"), recursive=True)
                + glob.glob(os.path.join(output_dir, "**", "*.webm"), recursive=True)
            )

        if not video_files:
            raise RuntimeError("No video file generated by SadTalker")

        video_files.sort(key=os.path.getmtime, reverse=True)
        return video_files[0]
